### ISSUE TITLE
Click the window to close the process will not exit

### ISSUE THREAD

**Issue by BlackDawnX** [nuitsjp/Wpf.Extensions.Hosting#1]
Click the window to close the process will not exit

**Comment by nuitsjp** [comment]
Thanks for the report!
I'll check back over the weekend. 
Please hold on a moment.

**Comment by nuitsjp** [comment]
Thanks!!! 
I was able to fix one issue. 
Take advantage of the new release. 

- https://www.nuget.org/packages/Wpf.Extensions.Hosting/1.1.2
